//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMICT.CSP.Web.TemplateConfig.CommunicationConfig {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CommunicationConfig {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Repeater CommunicationList;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton LinkButton1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton lbtnPreView;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton lbtnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlCATEGORY;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtCATEGORY;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trbig;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlsmallcategory;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtsmallcategory;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trsmall;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlSourceTemplate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSourceTemplate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSelected;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Repeater CommunicationDetailList;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidSaveModel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidCommunicationDetails;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidTemplateID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidsourceid;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidCommunicationID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidtipcontent;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidtitle;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidisedit;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnDelete;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnEdit;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnAddNew;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnFinish;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CommunicationConfig target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control3(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <thead>
                            <tr>
                                <th width=""47"">序号</th>
                                <th width=""300"">业务名称</th>
                                <th>源模板</th>
                                <th>目标模板</th>
                                <th width=""150"">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control5() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(2, 1);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                        <tr>\r\n                            <td>");
            @__ctrl.SetStaticString(1, "</td>\r\n                            <td>\r\n                                ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control5);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBind__control5(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            target.SetDataBoundString(0, global::System.Convert.ToString(Container.ItemIndex+1, global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__control6() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "lblName";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control6);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBinding__control6(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Literal dataBindingExpressionBuilderTarget;
            System.Web.UI.WebControls.RepeaterItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Literal)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString(Eval("Name") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control7() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(5, 4);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "</td>\r\n                            <td>\r\n                                ");
            @__ctrl.SetStaticString(1, "</td>\r\n                            <td>\r\n                                ");
            @__ctrl.SetStaticString(2, "</td>\r\n                            <td>\r\n                                <a id=\"l" +
                    "btnEdit\" onclick=\"editCommunication(\'");
            @__ctrl.SetStaticString(3, "\')\" href=\"javascript:void(0);\" class=\"operateBtn edit\"></a>\r\n                    " +
                    "            <a id=\"lbtnDelete\" onclick=\"deleteCommunication(\'");
            @__ctrl.SetStaticString(4, "\')\" href=\"javascript:void(0);\" class=\"operateBtn remove\"></a>\r\n                  " +
                    "          </td>\r\n                        </tr>\r\n                    ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control7);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBind__control7(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("SourceName"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("TargetName"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(2, global::System.Convert.ToString(Eval("CommunicationID"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(3, global::System.Convert.ToString(Eval("CommunicationID"), global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control4(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control5();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control6();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.DataBoundLiteralControl @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control7();
            @__parser.AddParsedSubObject(@__ctrl3);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlCommunicationList() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            this.CommunicationList = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control3));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control4));
            @__ctrl.ID = "CommunicationList";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlLinkButton1() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.LinkButton1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "LinkButton1";
            @__ctrl.CssClass = "guideBtn prevLink";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("上一步"));
            @__ctrl.Click -= new System.EventHandler(this.lbtnPrev_Click);
            @__ctrl.Click += new System.EventHandler(this.lbtnPrev_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbtnPreView() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbtnPreView = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbtnPreView";
            @__ctrl.CssClass = "guideBtn nextLink";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("预览"));
            @__ctrl.Click -= new System.EventHandler(this.lbtnPreView_Click);
            @__ctrl.Click += new System.EventHandler(this.lbtnPreView_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbtnSave() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbtnSave = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbtnSave";
            @__ctrl.CssClass = "guideBtn nextLink";
            @__ctrl.OnClientClick = "FinishTemplate();return false;";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("完成"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControltxtName() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.txtName = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "stepIpt w210 txtName");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            @__ctrl.ID = "txtName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "业务名称~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <label class=\"stepIptTxt\">报表大类：</label>"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlCATEGORY() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlCATEGORY = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlCATEGORY";
            @__ctrl.CssClass = "setDropIpt default w210 ddlCATEGORY";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "changecatebig();");
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlCATEGORY_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlCATEGORY_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCATEGORY() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCATEGORY = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCATEGORY";
            @__ctrl.CssClass = "txtDBName txtCATEGORY";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "报表大类~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlCATEGORY();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<span class=\"mustIcon\">*</span>\r\n                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtCATEGORY();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control11));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control11(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                <div id=\"div");
                     @__w.Write(txtCATEGORY.ClientID );

            @__w.Write("\"></div>\r\n            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control8(System.Web.UI.HtmlControls.HtmlTableCellCollection @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control9();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control10();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl3);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableRow @__BuildControltrbig() {
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableRow();
            this.trbig = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "trbig";
            this.@__BuildControl__control8(@__ctrl.Cells);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control13() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <label class=\"stepIptTxt\">报表细类：</label>"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlsmallcategory() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlsmallcategory = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlsmallcategory";
            @__ctrl.CssClass = "setDropIpt default w210 ddlsmallcategory";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "changesmallcategory();");
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlsmallcategory_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlsmallcategory_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtsmallcategory() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtsmallcategory = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtsmallcategory";
            @__ctrl.CssClass = "txtDBName txtsmallcategory";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "报表细类~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control14() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlsmallcategory();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <span class=\"mustIcon\">*</span>\r\n                "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtsmallcategory();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control15() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control15));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control15(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                <div id=\"div");
                     @__w.Write(txtsmallcategory.ClientID );

            @__w.Write("\"></div>\r\n            ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control12(System.Web.UI.HtmlControls.HtmlTableCellCollection @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control13();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control14();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control15();
            @__ctrl.Add(@__ctrl3);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableRow @__BuildControltrsmall() {
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableRow();
            this.trsmall = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "trsmall";
            this.@__BuildControl__control12(@__ctrl.Cells);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlSourceTemplate() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlSourceTemplate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlSourceTemplate";
            @__ctrl.CssClass = "setDropIpt default w210 ddlSourceTemplate";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "changeSourceTemplate(this);");
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlSourceTemplate_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlSourceTemplate_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSourceTemplate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSourceTemplate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSourceTemplate";
            @__ctrl.CssClass = "txtSourceTemplate";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "源模板~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSelected() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSelected = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSelected";
            @__ctrl.CssClass = "txtSelected";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control16(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <thead>
                                                <tr>
                                                    <th style=""width: 10%"">序号</th>
                                                    <th style=""width: 30%"">源列名</th>
                                                    <th style=""width: 30%"">源列类型</th>
                                                    <th style=""width: 30%"">目标列</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                        "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control18() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(3, 2);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                            <tr>\r\n                             " +
                    "                   <td>");
            @__ctrl.SetStaticString(1, "</td>\r\n                                                <td>");
            @__ctrl.SetStaticString(2, "</td>\r\n                                                <td>\r\n                    " +
                    "                                ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control18);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBind__control18(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            target.SetDataBoundString(0, global::System.Convert.ToString(Container.ItemIndex+1, global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("ColumnName"), global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__control19() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "lblSourceDataType";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__control20() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "lblColumnDataType";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control20);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBinding__control20(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Literal dataBindingExpressionBuilderTarget;
            System.Web.UI.WebControls.RepeaterItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Literal)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString(Eval("ColumnDataType") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__control21() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "lblTargetColumnName";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control21);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBinding__control21(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Literal dataBindingExpressionBuilderTarget;
            System.Web.UI.WebControls.RepeaterItem Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Literal)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString(Eval("TargetColumnName") , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControl__control22() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlTargetColumn";
            @__ctrl.CssClass = "setDropIpt default w210 ddlTargetColumn";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control17(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control18();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control19();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                    <div style=\"display: none\">" +
                        "\r\n                                                        "));
            global::System.Web.UI.WebControls.Literal @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control20();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                    </div>
                                                </td>
                                                <td>
                                                    <div style=""display: none"">
                                                        "));
            global::System.Web.UI.WebControls.Literal @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control21();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                    </div>\r\n                   " +
                        "                                 "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control22();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                </td>\r\n                        " +
                        "                    </tr>\r\n                                        "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlCommunicationDetailList() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            this.CommunicationDetailList = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control16));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control17));
            @__ctrl.ID = "CommunicationDetailList";
            @__ctrl.ItemDataBound -= new System.Web.UI.WebControls.RepeaterItemEventHandler(this.CommunicationDetailList_ItemDataBound);
            @__ctrl.ItemDataBound += new System.Web.UI.WebControls.RepeaterItemEventHandler(this.CommunicationDetailList_ItemDataBound);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidSaveModel() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidSaveModel = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidSaveModel";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidSaveModel");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidCommunicationDetails() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidCommunicationDetails = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidCommunicationDetails";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidCommunicationDetails");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidTemplateID() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidTemplateID = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidTemplateID";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidTemplateID");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidsourceid() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidsourceid = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidsourceid";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidsourceid");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidCommunicationID() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidCommunicationID = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidCommunicationID";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidCommunicationID");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidtipcontent() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidtipcontent = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidtipcontent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidtipcontent");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidtitle() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidtitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidtitle";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidtitle");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidisedit() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidisedit = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidisedit";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidisedit");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnDelete() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnDelete = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnDelete";
            @__ctrl.Click -= new System.EventHandler(this.btnDelete_Click);
            @__ctrl.Click += new System.EventHandler(this.btnDelete_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnEdit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnEdit = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnEdit";
            @__ctrl.Click -= new System.EventHandler(this.btnEdit_Click);
            @__ctrl.Click += new System.EventHandler(this.btnEdit_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnAddNew() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnAddNew = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnAddNew";
            @__ctrl.Click -= new System.EventHandler(this.btnAddNew_Click);
            @__ctrl.Click += new System.EventHandler(this.btnAddNew_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnFinish() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnFinish = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnFinish";
            @__ctrl.Click -= new System.EventHandler(this.btnFinish_Click);
            @__ctrl.Click += new System.EventHandler(this.btnFinish_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.Repeater @__ctrl1;
            @__ctrl1 = this.@__BuildControlCommunicationList();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.LinkButton @__ctrl2;
            @__ctrl2 = this.@__BuildControlLinkButton1();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.LinkButton @__ctrl3;
            @__ctrl3 = this.@__BuildControllbtnPreView();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.LinkButton @__ctrl4;
            @__ctrl4 = this.@__BuildControllbtnSave();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl5;
            @__ctrl5 = this.@__BuildControltxtName();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl6;
            @__ctrl6 = this.@__BuildControltrbig();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl7;
            @__ctrl7 = this.@__BuildControltrsmall();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.DropDownList @__ctrl8;
            @__ctrl8 = this.@__BuildControlddlSourceTemplate();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxtSourceTemplate();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            @__ctrl10 = this.@__BuildControltxtSelected();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.Repeater @__ctrl11;
            @__ctrl11 = this.@__BuildControlCommunicationDetailList();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl12;
            @__ctrl12 = this.@__BuildControlhidSaveModel();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl13;
            @__ctrl13 = this.@__BuildControlhidCommunicationDetails();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl14;
            @__ctrl14 = this.@__BuildControlhidTemplateID();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl15;
            @__ctrl15 = this.@__BuildControlhidsourceid();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl16;
            @__ctrl16 = this.@__BuildControlhidCommunicationID();
            @__parser.AddParsedSubObject(@__ctrl16);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl17;
            @__ctrl17 = this.@__BuildControlhidtipcontent();
            @__parser.AddParsedSubObject(@__ctrl17);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl18;
            @__ctrl18 = this.@__BuildControlhidtitle();
            @__parser.AddParsedSubObject(@__ctrl18);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl19;
            @__ctrl19 = this.@__BuildControlhidisedit();
            @__parser.AddParsedSubObject(@__ctrl19);
            global::System.Web.UI.WebControls.Button @__ctrl20;
            @__ctrl20 = this.@__BuildControlbtnDelete();
            @__parser.AddParsedSubObject(@__ctrl20);
            global::System.Web.UI.WebControls.Button @__ctrl21;
            @__ctrl21 = this.@__BuildControlbtnEdit();
            @__parser.AddParsedSubObject(@__ctrl21);
            global::System.Web.UI.WebControls.Button @__ctrl22;
            @__ctrl22 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl22);
            global::System.Web.UI.WebControls.Button @__ctrl23;
            @__ctrl23 = this.@__BuildControlbtnAddNew();
            @__parser.AddParsedSubObject(@__ctrl23);
            global::System.Web.UI.WebControls.Button @__ctrl24;
            @__ctrl24 = this.@__BuildControlbtnFinish();
            @__parser.AddParsedSubObject(@__ctrl24);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control2));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"
        <div class=""progressBox"">
            <ul class=""progressStepBox"">
                <li>
                    <div class=""stepBox stepPrev"">
                        <p>1.基本信息配置</p>
                        <span></span>
                    </div>
                </li>
                <li>
                    <div class=""stepBox stepPrev"">
                        <p>2.配置数据源</p>
                        <span></span>
                    </div>
                </li>
                <li>
                    <div class=""stepBox stepPrev"">
                        <p>3.配置展示方式</p>
                        <span></span>
                    </div>
                </li>
                <li>
                    <div class=""stepBox stepPrev"">
                        <p>4.配置筛选条件</p>
                        <span></span>
                    </div>
                </li>
                <li>
                    <div class=""stepBox stepcurrent"">
                        <p>5.配置业务信息查询通信</p>
                    </div>
                </li>
            </ul>
        </div>

        <div class=""stepOperateBox"">
            <p class=""stepTitle columnshow"" id=""columntitle"">通信关联配置</p>
            <table class=""tableOne tableLayout columnshow"" id=""columncontent"">
                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write(@"
                </tbody>
            </table>
            <div>
                <button id=""btnAdd"" onclick=""return addCommunicationConfig();"" class=""addBtn fLeft""></button>
            </div>
            <div class=""operateBtnBox operateBtnLayout"">
                ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write(@"
            </div>
        </div>
        
        <div class=""shade""></div>
        <!-- 选择列弹窗 Start -->
        <div class=""toolTipBox communicationdetaildiv"" style=""width: 540px;height:580px;"">
            <div class=""toolTipContent"" style=""height:540px;overflow-y:auto;"">
                <div class=""operateBtnBox toolOperateLayout"" style=""text-align:right;padding-top:0px;padding-bottom:20px"">
                    <a class=""guideBtn nextLink"" href=""javascript:void(0)"" onclick=""saveDetail();"">确定</a>
                    <a class=""guideBtn prevLink"" href=""javascript:void(0)"" onclick=""closedetailwin();"">取消</a>
                </div>
                <div class=""cutOffRule clearBoth""></div>
                <div class=""toolTipArea"" style=""padding-top:20px"">
                    <table class=""tableTwo"" style=""width: 100%"">
                        <tr>
                            <td>
                                <label class=""stepIptTxt"">业务名称：</label></td>
                            <td>
                                ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n                                <span class=\"mustIcon\">*</span>\r\n              " +
                    "              </td>\r\n                            <td>\r\n                         " +
                    "       <div id=\"div");
                                     @__w.Write(txtName.ClientID );

            @__w.Write("\"></div>\r\n                            </td>\r\n                        </tr>\r\n     " +
                    "                   ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n                        <tr>\r\n                            <td>\r\n               " +
                    "                 <label class=\"stepIptTxt\">源模板：</label></td>\r\n                  " +
                    "          <td>\r\n                                ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n                                <span class=\"mustIcon\">*</span>\r\n              " +
                    "                  ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n                            </td>\r\n                            <td>\r\n          " +
                    "                      <div id=\"div");
                                     @__w.Write(txtSourceTemplate.ClientID );

            @__w.Write(@"""></div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=""2"">列映射配置<span style=""color: red; padding-left: 50px"">最多选择5个映射关系</span>
                            </td>
                            <td>
                                ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write(@"
                            </td>
                        </tr>
                        <tr>
                            <td colspan=""3"">
                                <table class=""tableOne tableLayout columnshow"" id=""detailcontent"">
                                    ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write(@"
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class=""cutOffRule clearBoth""></div>
                <div class=""operateBtnBox toolOperateLayout"" style=""text-align:right;"">
                    <a class=""guideBtn nextLink"" href=""javascript:void(0)"" onclick=""saveDetail();"">确定</a>
                    <a class=""guideBtn prevLink"" href=""javascript:void(0)"" onclick=""closedetailwin();"">取消</a>
                </div>

            </div>
        </div>
        <!-- 选择列弹窗 End -->
        ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[16].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[17].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[18].RenderControl(@__w);
            @__w.Write("\r\n        <div style=\"display: none;\">\r\n            ");
            parameterContainer.Controls[19].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[20].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[21].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[22].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[23].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n    ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanel1 = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "UpdatePanel1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::CMICT.CSP.Web.TemplateConfig.CommunicationConfig.CommunicationConfig @__ctrl) {
            global::System.Web.UI.UpdatePanel @__ctrl1;
            @__ctrl1 = this.@__BuildControlUpdatePanel1();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n<script type=\"text/javascript\">\r\n    function changecatebig() {\r\n        $(\".tx" +
                    "tCATEGORY\").val($(\".ddlCATEGORY option:selected\").val());\r\n        $(\".txtCATEGO" +
                    "RY\").change();\r\n    }\r\n\r\n    function changesmallcategory() {\r\n        $(\".txtsm" +
                    "allcategory\").val($(\".ddlsmallcategory option:selected\").val());\r\n        $(\".tx" +
                    "tsmallcategory\").change();\r\n    }\r\n    $(function ($) {\r\n        addtiptodbname(" +
                    ");\r\n        $(\".hidtitle\").val($(document).attr(\"title\"));\r\n    });\r\n    //给数据源下" +
                    "拉加title\r\n    function addtiptodbname() {\r\n        var sourcenametip = $(\".hidtip" +
                    "content\").val();\r\n        if ($.trim(sourcenametip) != \"\") {\r\n            var st" +
                    "iplist = sourcenametip.split(\'!\');\r\n            $(\"div[id*=\'ddlSourceTemplate\']\"" +
                    ").find(\"a\").each(function () {\r\n                if ($(this).attr(\"data-dk-dropdo" +
                    "wn-value\") != undefined && $(this).attr(\"data-dk-dropdown-value\") != null && $(t" +
                    "his).attr(\"data-dk-dropdown-value\") != \"\") {\r\n                    var atipname =" +
                    " $(this).attr(\"data-dk-dropdown-value\");\r\n                    for (var i = 0; i " +
                    "< stiplist.length; i++) {\r\n                        if (stiplist[i].indexOf(atipn" +
                    "ame) != -1) {\r\n                            $(this).attr(\"title\", stiplist[i].spl" +
                    "it(\',\')[1]);\r\n                            break;\r\n                        }\r\n   " +
                    "                 }\r\n                }\r\n            });\r\n        }\r\n        $(\"di" +
                    "v[id*=\'ddlCATEGORY\']\").find(\"a\").each(function () {\r\n            var atipname = " +
                    "$(this).html();\r\n            $(this).attr(\"title\", atipname).addClass(\"costDes\")" +
                    ";\r\n        });\r\n        $(\"div[id*=\'ddlsmallcategory\']\").find(\"a\").each(function" +
                    " () {\r\n            var atipname = $(this).html();\r\n            $(this).attr(\"tit" +
                    "le\", atipname).addClass(\"costDes\");\r\n        });\r\n    }\r\n    var prm = Sys.WebFo" +
                    "rms.PageRequestManager.getInstance();\r\n    prm.add_beginRequest(function () {\r\n\r" +
                    "\n    });\r\n    prm.add_endRequest(function (sender, args) {\r\n        args.set_err" +
                    "orHandled(true);\r\n        try {\r\n            if ($(\'.default\').length > 0) {\r\n  " +
                    "              $(\'.default\').dropkick();\r\n                addtiptodbname();\r\n    " +
                    "        }\r\n            $(document).attr(\"title\", $(\".hidtitle\").val());\r\n       " +
                    " } catch (err) {\r\n\r\n        }\r\n    });\r\n    var yes = \'确定\';\r\n    var no = \'取消\';\r" +
                    "\n    function FinishTemplate() {\r\n        var msgs = \"您确定完成吗？\";\r\n        var tip" +
                    "c = $(\".hidisedit\").val();\r\n        if (tipc == \"edit\") {\r\n            msgs = \"修" +
                    "改模板配置会影响业务逻辑的查询，您确定要完成吗？\";\r\n        }\r\n        $.layer({\r\n            shade: [0." +
                    "5, \'#000\', true],\r\n            area: [\'auto\', \'auto\'],\r\n            dialog: {\r\n " +
                    "               msg: msgs,\r\n                btns: 2,\r\n                type: 4,\r\n " +
                    "               btn: [yes, no],\r\n                yes: function (index) {\r\n       " +
                    "             $(\"#");
                @__w.Write(btnFinish.ClientID);

            @__w.Write(@""").click();
                    layer.close(index);
                },
                no: function (index) {
                    layer.close(index);
                }
            }
        });
    }

    function addCommunicationConfig() {
        $("".hidSaveModel"").val(""add"");
        $(""#");
    @__w.Write(btnAddNew.ClientID);

            @__w.Write(@""").click();
        return false;
    }

    function changeSourceTemplate(ctrl) {
        $("".txtSourceTemplate"").val($(ctrl).val());
    }

    function editCommunication(communicationId) {
        $("".hidCommunicationID"").val(communicationId);
        $("".hidSaveModel"").val(""edit"");
        $(""#");
    @__w.Write(btnEdit.ClientID);

            @__w.Write(@""").click();
    }

    function showDetail() {
        $("".shade"").show();
        $("".communicationdetaildiv"").show();
    }

    function closedetailwin() {
        $("".shade"").hide();
        $("".communicationdetaildiv"").hide();
    }

    function deleteCommunication(communicationId) {
        $("".hidCommunicationID"").val(communicationId);
        $.layer({
            shade: [0.5, '#000', true],
            area: ['auto', 'auto'],
            dialog: {
                msg: '您确定删除吗？',
                btns: 2,
                type: 4,
                btn: [yes, no],
                yes: function (index) {
                    $(""#");
                @__w.Write(btnDelete.ClientID);

            @__w.Write("\").click();\r\n                    layer.close(index);\r\n                },\r\n       " +
                    "         no: function (index) {\r\n                    layer.close(index);\r\n      " +
                    "          }\r\n            }\r\n        });\r\n    }\r\n\r\n    function showMessage(msg,a" +
                    "type) {\r\n        layer.alert(msg, atype);\r\n    }\r\n    //将目标列下拉框选择为空\r\n    functio" +
                    "n resettargetcolumn(obj) {\r\n        $(obj).parent().find(\".dk_option_current\").a" +
                    "ttr(\"class\", \"\");\r\n        $(obj).parent().find(\"a\").each(function () {\r\n       " +
                    "     if ($(this).attr(\"data-dk-dropdown-value\") != undefined && $(this).attr(\"da" +
                    "ta-dk-dropdown-value\") != null) {\r\n                if ($.trim($(this).attr(\"data" +
                    "-dk-dropdown-value\")) == \"\") {\r\n                    $(this).parent().attr(\"class" +
                    "\", \"dk_option_current\");\r\n                    $(this).parent().parent().parent()" +
                    ".prev().text($(this).text());\r\n                }\r\n            }\r\n        });\r\n  " +
                    "  }\r\n    function matchColumnDataType(ctrltargetColumn, sourceDataType) {\r\n     " +
                    "   var isNotMatch = false;\r\n        var targetColumnType = $.trim($(ctrltargetCo" +
                    "lumn).val().split(\'-\')[1]);\r\n        if (targetColumnType) {\r\n            if (ta" +
                    "rgetColumnType != sourceDataType) {\r\n                isNotMatch = true;\r\n       " +
                    "         $.layer({\r\n                    shade: [0.5, \'#000\', true],\r\n           " +
                    "         area: [\'auto\', \'auto\'],\r\n                    dialog: {\r\n               " +
                    "         msg: \"选择的目标列类型与源列类型不匹配，请重新选择！\",\r\n                        btns: 1,\r\n    " +
                    "                    type: 4,\r\n                        btn: [\'确定\'],\r\n            " +
                    "            yes: function (index) {\r\n                            layer.close(ind" +
                    "ex);\r\n                            resettargetcolumn(ctrltargetColumn);\r\n        " +
                    "                    //$(ctrltargetColumn)[0].selectedIndex = 0;\r\n               " +
                    "         }\r\n                    },\r\n                    close: function (index) " +
                    "{\r\n                        layer.close(index);\r\n                        resettar" +
                    "getcolumn(ctrltargetColumn);\r\n                        //$(ctrltargetColumn)[0].s" +
                    "electedIndex = 0;\r\n                    }\r\n                });\r\n            }\r\n  " +
                    "      }\r\n\r\n        if (!isNotMatch) {\r\n            var selectCount = 0;\r\n       " +
                    "     $(\".ddlTargetColumn\").each(function () {\r\n                if ($(this).val()" +
                    ") {\r\n                    selectCount++;\r\n                }\r\n            });\r\n   " +
                    "         if (selectCount == 0) {\r\n                $(\".txtSelected\").val(\"\");\r\n  " +
                    "          }\r\n            else {\r\n                $(\".txtSelected\").val(selectCou" +
                    "nt);\r\n            }\r\n            //if (selectCount >= 5) {\r\n            //    $(" +
                    "\".ddlTargetColumn\").each(function () {\r\n            //        var sValue = $(thi" +
                    "s).val();\r\n            //        if (sValue == \"\") {\r\n            //            " +
                    "$(this).attr(\"disabled\", \"disabled\");\r\n            //        }\r\n            //  " +
                    "  });\r\n            //}\r\n            //else {\r\n            //    $(\".ddlTargetCol" +
                    "umn\").each(function () {\r\n            //        var sValue = $(this).val();\r\n   " +
                    "         //        if (sValue == \"\") {\r\n            //            $(this).remove" +
                    "Attr(\"disabled\");\r\n            //        }\r\n            //    });\r\n            /" +
                    "/}\r\n        }\r\n    }\r\n\r\n    function saveDetail() {\r\n        if ($(\".txtSelected" +
                    "\").val() == \"\") {\r\n            layer.alert(\"请至少选择一项目标列！\");\r\n        }\r\n        e" +
                    "lse {\r\n            var tcount = 0;\r\n            $(\".ddlTargetColumn\").each(funct" +
                    "ion () {\r\n                if ($(this).val()) {\r\n                    tcount++;\r\n " +
                    "               }\r\n            });\r\n            if (tcount > 5) {\r\n              " +
                    "  layer.alert(\"映射关系不能多于5个！\");\r\n            }else{\r\n            var b_return = ch" +
                    "eckForm(document.forms.item(0, null));\r\n            var savemodel = $(\".hidSaveM" +
                    "odel\").val();\r\n            var msg = savemodel == \"add\" ? \"您确定要新增吗？\" : \"您确定要修改吗？" +
                    "\";\r\n            if (b_return) {\r\n                $.layer({\r\n                    " +
                    "shade: [0.5, \'#000\', true],\r\n                    area: [\'auto\', \'auto\'],\r\n      " +
                    "              dialog: {\r\n                        msg: msg,\r\n                    " +
                    "    btns: 2,\r\n                        type: 4,\r\n                        btn: [ye" +
                    "s, no],\r\n                        yes: function (index) {\r\n                      " +
                    "      var details = \"\";\r\n\r\n                            $(\"div[id*=\'ddlTargetColu" +
                    "mn\']\").each(function () {\r\n                                if ($(this).find(\".dk" +
                    "_option_current\").length > 0) {\r\n                                    var sv = $." +
                    "trim($(this).find(\".dk_option_current\").children(\'a\').eq(0).attr(\"data-dk-dropdo" +
                    "wn-value\"));\r\n                                    if (sv != \"\") {\r\n             " +
                    "                           var targetColumn = sv;\r\n                             " +
                    "           if (targetColumn.indexOf(\'-\') >= 0) {\r\n                              " +
                    "              targetColumn = $.trim(targetColumn.split(\'-\')[0]);\r\n              " +
                    "                          }\r\n\r\n                                        if (targe" +
                    "tColumn) {\r\n                                            var sourceColumn = $(thi" +
                    "s).parent().parent().children().get(1).innerText;\r\n                             " +
                    "               if (details) {\r\n                                                d" +
                    "etails += \"|\" + sourceColumn + \";\" + targetColumn;\r\n                            " +
                    "                }\r\n                                            else {\r\n         " +
                    "                                       details = sourceColumn + \";\" + targetColu" +
                    "mn;\r\n                                            }\r\n                            " +
                    "            }\r\n                                    }\r\n                          " +
                    "      }\r\n\r\n                            });\r\n                            $(\".hidC" +
                    "ommunicationDetails\").val(details); \r\n                            $(\"#");
                        @__w.Write(btnSave.ClientID);

            @__w.Write(@""").click();
                            layer.close(index);
                        }

                    },
                    close: function (index) {
                        layer.close(index);
                    }
                });
            }
        }
    }
    }
    //预览
    function GotoPreView() {
        var temid = $.trim($("".hidTemplateID"").val());
        if (temid != """") {
            //window.open(""PreView.aspx?templateID="" + temid);
            var w = window.open();
            //setTimeout(function () {
                w.location = ""PreView.aspx?templateID="" + temid;
            //}, 300);

            return false;
            //ExecuteOrDelayUntilScriptLoaded(function () {
            //    var options = SP.UI.$create_DialogOptions();
            //    options.title = ""预览"";
            //    options.width = 1000;
            //    options.height = 700;
            //    options.url = ""PreView.aspx?templateID=""+temid;
            //    //options.dialogReturnValueCallback = Function.createDelegate(null, UpdateRightContent);
            //    SP.UI.ModalDialog.showModalDialog(options);
            //}, 'sp.js');
        } else {
            layer.alert('未获取到模板信息,无法预览！', 8);
        }
        return false;
    }
</script>
");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
