//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMICT.CSP.Web.BusinessOnlineServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cmict.com/", ConfigurationName="BusinessOnlineServices.QGCostcoSoap")]
    public interface QGCostcoSoap {
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 applyData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/costcoAdd", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponse costcoAdd(CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/costcoAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponse> costcoAddAsync(CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 userid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/checkUser", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.checkUserResponse checkUser(CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/checkUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.checkUserResponse> checkUserAsync(CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 ctnno 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/queryCtnno", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponse queryCtnno(CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/queryCtnno", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponse> queryCtnnoAsync(CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 ctnno 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/submitCheck", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponse submitCheck(CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/submitCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponse> submitCheckAsync(CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 ctnno 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/TosSubmitCheck", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponse TosSubmitCheck(CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/TosSubmitCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponse> TosSubmitCheckAsync(CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 xmlinput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/TOS04", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.TOS04Response TOS04(CMICT.CSP.Web.BusinessOnlineServices.TOS04Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/TOS04", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.TOS04Response> TOS04Async(CMICT.CSP.Web.BusinessOnlineServices.TOS04Request request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 toNode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/callNPP4EDI", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponse callNPP4EDI(CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/callNPP4EDI", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponse> callNPP4EDIAsync(CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/getBookTime", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponse getBookTime(CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/getBookTime", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponse> getBookTimeAsync(CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/reserve", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.reserveResponse reserve(CMICT.CSP.Web.BusinessOnlineServices.reserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/reserve", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.reserveResponse> reserveAsync(CMICT.CSP.Web.BusinessOnlineServices.reserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/reserveContainers", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponse reserveContainers(CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/reserveContainers", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponse> reserveContainersAsync(CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 outDateStar 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/costcoOutGateSearch", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponse costcoOutGateSearch(CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/costcoOutGateSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponse> costcoOutGateSearchAsync(CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest request);
        
        // CODEGEN: 命名空间 http://service.cmict.com/ 的元素名称 containerId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/costcoContainerSearch", ReplyAction="*")]
        CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponse costcoContainerSearch(CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.cmict.com/cmictbts/costcoContainerSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponse> costcoContainerSearchAsync(CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costcoAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costcoAdd", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequestBody Body;
        
        public costcoAddRequest() {
        }
        
        public costcoAddRequest(CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class costcoAddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applyData;
        
        public costcoAddRequestBody() {
        }
        
        public costcoAddRequestBody(string applyData) {
            this.applyData = applyData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costcoAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costcoAddResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponseBody Body;
        
        public costcoAddResponse() {
        }
        
        public costcoAddResponse(CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class costcoAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string costcoAddResult;
        
        public costcoAddResponseBody() {
        }
        
        public costcoAddResponseBody(string costcoAddResult) {
            this.costcoAddResult = costcoAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUser", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.checkUserRequestBody Body;
        
        public checkUserRequest() {
        }
        
        public checkUserRequest(CMICT.CSP.Web.BusinessOnlineServices.checkUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class checkUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public checkUserRequestBody() {
        }
        
        public checkUserRequestBody(string userid, string password) {
            this.userid = userid;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUserResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.checkUserResponseBody Body;
        
        public checkUserResponse() {
        }
        
        public checkUserResponse(CMICT.CSP.Web.BusinessOnlineServices.checkUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class checkUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkUserResult;
        
        public checkUserResponseBody() {
        }
        
        public checkUserResponseBody(string checkUserResult) {
            this.checkUserResult = checkUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryCtnnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryCtnno", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequestBody Body;
        
        public queryCtnnoRequest() {
        }
        
        public queryCtnnoRequest(CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class queryCtnnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ctnno;
        
        public queryCtnnoRequestBody() {
        }
        
        public queryCtnnoRequestBody(string ctnno) {
            this.ctnno = ctnno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryCtnnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryCtnnoResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponseBody Body;
        
        public queryCtnnoResponse() {
        }
        
        public queryCtnnoResponse(CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class queryCtnnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string queryCtnnoResult;
        
        public queryCtnnoResponseBody() {
        }
        
        public queryCtnnoResponseBody(string queryCtnnoResult) {
            this.queryCtnnoResult = queryCtnnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitCheck", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequestBody Body;
        
        public submitCheckRequest() {
        }
        
        public submitCheckRequest(CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class submitCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ctnno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vesselcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string voyage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string isDataOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string isLocationOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string isCtnOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string realSealNos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string userid;
        
        public submitCheckRequestBody() {
        }
        
        public submitCheckRequestBody(string ctnno, string vesselcode, string voyage, string isDataOK, string isLocationOK, string isCtnOK, string realSealNos, string userid) {
            this.ctnno = ctnno;
            this.vesselcode = vesselcode;
            this.voyage = voyage;
            this.isDataOK = isDataOK;
            this.isLocationOK = isLocationOK;
            this.isCtnOK = isCtnOK;
            this.realSealNos = realSealNos;
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitCheckResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponseBody Body;
        
        public submitCheckResponse() {
        }
        
        public submitCheckResponse(CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class submitCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string submitCheckResult;
        
        public submitCheckResponseBody() {
        }
        
        public submitCheckResponseBody(string submitCheckResult) {
            this.submitCheckResult = submitCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TosSubmitCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TosSubmitCheck", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequestBody Body;
        
        public TosSubmitCheckRequest() {
        }
        
        public TosSubmitCheckRequest(CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class TosSubmitCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ctnno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vesselcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string voyage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string isDataOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string isLocationOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string isCtnOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string realSealNos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long edicontainerInfoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long containerrecid;
        
        public TosSubmitCheckRequestBody() {
        }
        
        public TosSubmitCheckRequestBody(string ctnno, string vesselcode, string voyage, string isDataOK, string isLocationOK, string isCtnOK, string realSealNos, string userid, long edicontainerInfoID, long containerrecid) {
            this.ctnno = ctnno;
            this.vesselcode = vesselcode;
            this.voyage = voyage;
            this.isDataOK = isDataOK;
            this.isLocationOK = isLocationOK;
            this.isCtnOK = isCtnOK;
            this.realSealNos = realSealNos;
            this.userid = userid;
            this.edicontainerInfoID = edicontainerInfoID;
            this.containerrecid = containerrecid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TosSubmitCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TosSubmitCheckResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponseBody Body;
        
        public TosSubmitCheckResponse() {
        }
        
        public TosSubmitCheckResponse(CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class TosSubmitCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TosSubmitCheckResult;
        
        public TosSubmitCheckResponseBody() {
        }
        
        public TosSubmitCheckResponseBody(string TosSubmitCheckResult) {
            this.TosSubmitCheckResult = TosSubmitCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TOS04Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TOS04", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.TOS04RequestBody Body;
        
        public TOS04Request() {
        }
        
        public TOS04Request(CMICT.CSP.Web.BusinessOnlineServices.TOS04RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class TOS04RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlinput;
        
        public TOS04RequestBody() {
        }
        
        public TOS04RequestBody(string xmlinput) {
            this.xmlinput = xmlinput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TOS04Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TOS04Response", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.TOS04ResponseBody Body;
        
        public TOS04Response() {
        }
        
        public TOS04Response(CMICT.CSP.Web.BusinessOnlineServices.TOS04ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class TOS04ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TOS04Result;
        
        public TOS04ResponseBody() {
        }
        
        public TOS04ResponseBody(string TOS04Result) {
            this.TOS04Result = TOS04Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class callNPP4EDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="callNPP4EDI", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequestBody Body;
        
        public callNPP4EDIRequest() {
        }
        
        public callNPP4EDIRequest(CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class callNPP4EDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toNode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string esbID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data;
        
        public callNPP4EDIRequestBody() {
        }
        
        public callNPP4EDIRequestBody(string toNode, string esbID, string data) {
            this.toNode = toNode;
            this.esbID = esbID;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class callNPP4EDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="callNPP4EDIResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponseBody Body;
        
        public callNPP4EDIResponse() {
        }
        
        public callNPP4EDIResponse(CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class callNPP4EDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callNPP4EDIResult;
        
        public callNPP4EDIResponseBody() {
        }
        
        public callNPP4EDIResponseBody(string callNPP4EDIResult) {
            this.callNPP4EDIResult = callNPP4EDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBookTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBookTime", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequestBody Body;
        
        public getBookTimeRequest() {
        }
        
        public getBookTimeRequest(CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class getBookTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string preDate;
        
        public getBookTimeRequestBody() {
        }
        
        public getBookTimeRequestBody(string preDate) {
            this.preDate = preDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBookTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBookTimeResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponseBody Body;
        
        public getBookTimeResponse() {
        }
        
        public getBookTimeResponse(CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class getBookTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getBookTimeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorCode;
        
        public getBookTimeResponseBody() {
        }
        
        public getBookTimeResponseBody(string getBookTimeResult, string errorMsg, string errorCode) {
            this.getBookTimeResult = getBookTimeResult;
            this.errorMsg = errorMsg;
            this.errorCode = errorCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reserveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reserve", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.reserveRequestBody Body;
        
        public reserveRequest() {
        }
        
        public reserveRequest(CMICT.CSP.Web.BusinessOnlineServices.reserveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class reserveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string containerNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bLNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string reserved;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string handled;
        
        public reserveRequestBody() {
        }
        
        public reserveRequestBody(string containerNo, string bLNo, string reserved, string handled) {
            this.containerNo = containerNo;
            this.bLNo = bLNo;
            this.reserved = reserved;
            this.handled = handled;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reserveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reserveResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.reserveResponseBody Body;
        
        public reserveResponse() {
        }
        
        public reserveResponse(CMICT.CSP.Web.BusinessOnlineServices.reserveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class reserveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reserveResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorCode;
        
        public reserveResponseBody() {
        }
        
        public reserveResponseBody(string reserveResult, string errorMsg, string errorCode) {
            this.reserveResult = reserveResult;
            this.errorMsg = errorMsg;
            this.errorCode = errorCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reserveContainersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reserveContainers", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequestBody Body;
        
        public reserveContainersRequest() {
        }
        
        public reserveContainersRequest(CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class reserveContainersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string containers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reserveDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string linkman;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phone;
        
        public reserveContainersRequestBody() {
        }
        
        public reserveContainersRequestBody(string containers, string reserveDate, string customer, string linkman, string phone) {
            this.containers = containers;
            this.reserveDate = reserveDate;
            this.customer = customer;
            this.linkman = linkman;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reserveContainersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reserveContainersResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponseBody Body;
        
        public reserveContainersResponse() {
        }
        
        public reserveContainersResponse(CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class reserveContainersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reserveContainersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorCode;
        
        public reserveContainersResponseBody() {
        }
        
        public reserveContainersResponseBody(string reserveContainersResult, string errorMsg, string errorCode) {
            this.reserveContainersResult = reserveContainersResult;
            this.errorMsg = errorMsg;
            this.errorCode = errorCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costcoOutGateSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costcoOutGateSearch", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequestBody Body;
        
        public costcoOutGateSearchRequest() {
        }
        
        public costcoOutGateSearchRequest(CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class costcoOutGateSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outDateStar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string outDateEnds;
        
        public costcoOutGateSearchRequestBody() {
        }
        
        public costcoOutGateSearchRequestBody(string outDateStar, string outDateEnds) {
            this.outDateStar = outDateStar;
            this.outDateEnds = outDateEnds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costcoOutGateSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costcoOutGateSearchResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponseBody Body;
        
        public costcoOutGateSearchResponse() {
        }
        
        public costcoOutGateSearchResponse(CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class costcoOutGateSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string costcoOutGateSearchResult;
        
        public costcoOutGateSearchResponseBody() {
        }
        
        public costcoOutGateSearchResponseBody(string costcoOutGateSearchResult) {
            this.costcoOutGateSearchResult = costcoOutGateSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costcoContainerSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costcoContainerSearch", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequestBody Body;
        
        public costcoContainerSearchRequest() {
        }
        
        public costcoContainerSearchRequest(CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class costcoContainerSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string containerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string businessType;
        
        public costcoContainerSearchRequestBody() {
        }
        
        public costcoContainerSearchRequestBody(string containerId, string businessType) {
            this.containerId = containerId;
            this.businessType = businessType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costcoContainerSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costcoContainerSearchResponse", Namespace="http://service.cmict.com/", Order=0)]
        public CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponseBody Body;
        
        public costcoContainerSearchResponse() {
        }
        
        public costcoContainerSearchResponse(CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.cmict.com/")]
    public partial class costcoContainerSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string costcoContainerSearchResult;
        
        public costcoContainerSearchResponseBody() {
        }
        
        public costcoContainerSearchResponseBody(string costcoContainerSearchResult) {
            this.costcoContainerSearchResult = costcoContainerSearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QGCostcoSoapChannel : CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QGCostcoSoapClient : System.ServiceModel.ClientBase<CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap>, CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap {
        
        public QGCostcoSoapClient() {
        }
        
        public QGCostcoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QGCostcoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QGCostcoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QGCostcoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.costcoAdd(CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest request) {
            return base.Channel.costcoAdd(request);
        }
        
        public string costcoAdd(string applyData) {
            CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequestBody();
            inValue.Body.applyData = applyData;
            CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).costcoAdd(inValue);
            return retVal.Body.costcoAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.costcoAddAsync(CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest request) {
            return base.Channel.costcoAddAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoAddResponse> costcoAddAsync(string applyData) {
            CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.costcoAddRequestBody();
            inValue.Body.applyData = applyData;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).costcoAddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.checkUserResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.checkUser(CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest request) {
            return base.Channel.checkUser(request);
        }
        
        public string checkUser(string userid, string password) {
            CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.checkUserRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.password = password;
            CMICT.CSP.Web.BusinessOnlineServices.checkUserResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).checkUser(inValue);
            return retVal.Body.checkUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.checkUserResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.checkUserAsync(CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest request) {
            return base.Channel.checkUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.checkUserResponse> checkUserAsync(string userid, string password) {
            CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.checkUserRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.checkUserRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.password = password;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).checkUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.queryCtnno(CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest request) {
            return base.Channel.queryCtnno(request);
        }
        
        public string queryCtnno(string ctnno) {
            CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequestBody();
            inValue.Body.ctnno = ctnno;
            CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).queryCtnno(inValue);
            return retVal.Body.queryCtnnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.queryCtnnoAsync(CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest request) {
            return base.Channel.queryCtnnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoResponse> queryCtnnoAsync(string ctnno) {
            CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.queryCtnnoRequestBody();
            inValue.Body.ctnno = ctnno;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).queryCtnnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.submitCheck(CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest request) {
            return base.Channel.submitCheck(request);
        }
        
        public string submitCheck(string ctnno, string vesselcode, string voyage, string isDataOK, string isLocationOK, string isCtnOK, string realSealNos, string userid) {
            CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequestBody();
            inValue.Body.ctnno = ctnno;
            inValue.Body.vesselcode = vesselcode;
            inValue.Body.voyage = voyage;
            inValue.Body.isDataOK = isDataOK;
            inValue.Body.isLocationOK = isLocationOK;
            inValue.Body.isCtnOK = isCtnOK;
            inValue.Body.realSealNos = realSealNos;
            inValue.Body.userid = userid;
            CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).submitCheck(inValue);
            return retVal.Body.submitCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.submitCheckAsync(CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest request) {
            return base.Channel.submitCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.submitCheckResponse> submitCheckAsync(string ctnno, string vesselcode, string voyage, string isDataOK, string isLocationOK, string isCtnOK, string realSealNos, string userid) {
            CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.submitCheckRequestBody();
            inValue.Body.ctnno = ctnno;
            inValue.Body.vesselcode = vesselcode;
            inValue.Body.voyage = voyage;
            inValue.Body.isDataOK = isDataOK;
            inValue.Body.isLocationOK = isLocationOK;
            inValue.Body.isCtnOK = isCtnOK;
            inValue.Body.realSealNos = realSealNos;
            inValue.Body.userid = userid;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).submitCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.TosSubmitCheck(CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest request) {
            return base.Channel.TosSubmitCheck(request);
        }
        
        public string TosSubmitCheck(string ctnno, string vesselcode, string voyage, string isDataOK, string isLocationOK, string isCtnOK, string realSealNos, string userid, long edicontainerInfoID, long containerrecid) {
            CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequestBody();
            inValue.Body.ctnno = ctnno;
            inValue.Body.vesselcode = vesselcode;
            inValue.Body.voyage = voyage;
            inValue.Body.isDataOK = isDataOK;
            inValue.Body.isLocationOK = isLocationOK;
            inValue.Body.isCtnOK = isCtnOK;
            inValue.Body.realSealNos = realSealNos;
            inValue.Body.userid = userid;
            inValue.Body.edicontainerInfoID = edicontainerInfoID;
            inValue.Body.containerrecid = containerrecid;
            CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).TosSubmitCheck(inValue);
            return retVal.Body.TosSubmitCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.TosSubmitCheckAsync(CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest request) {
            return base.Channel.TosSubmitCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckResponse> TosSubmitCheckAsync(string ctnno, string vesselcode, string voyage, string isDataOK, string isLocationOK, string isCtnOK, string realSealNos, string userid, long edicontainerInfoID, long containerrecid) {
            CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.TosSubmitCheckRequestBody();
            inValue.Body.ctnno = ctnno;
            inValue.Body.vesselcode = vesselcode;
            inValue.Body.voyage = voyage;
            inValue.Body.isDataOK = isDataOK;
            inValue.Body.isLocationOK = isLocationOK;
            inValue.Body.isCtnOK = isCtnOK;
            inValue.Body.realSealNos = realSealNos;
            inValue.Body.userid = userid;
            inValue.Body.edicontainerInfoID = edicontainerInfoID;
            inValue.Body.containerrecid = containerrecid;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).TosSubmitCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.TOS04Response CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.TOS04(CMICT.CSP.Web.BusinessOnlineServices.TOS04Request request) {
            return base.Channel.TOS04(request);
        }
        
        public string TOS04(string xmlinput) {
            CMICT.CSP.Web.BusinessOnlineServices.TOS04Request inValue = new CMICT.CSP.Web.BusinessOnlineServices.TOS04Request();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.TOS04RequestBody();
            inValue.Body.xmlinput = xmlinput;
            CMICT.CSP.Web.BusinessOnlineServices.TOS04Response retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).TOS04(inValue);
            return retVal.Body.TOS04Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.TOS04Response> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.TOS04Async(CMICT.CSP.Web.BusinessOnlineServices.TOS04Request request) {
            return base.Channel.TOS04Async(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.TOS04Response> TOS04Async(string xmlinput) {
            CMICT.CSP.Web.BusinessOnlineServices.TOS04Request inValue = new CMICT.CSP.Web.BusinessOnlineServices.TOS04Request();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.TOS04RequestBody();
            inValue.Body.xmlinput = xmlinput;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).TOS04Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.callNPP4EDI(CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest request) {
            return base.Channel.callNPP4EDI(request);
        }
        
        public string callNPP4EDI(string toNode, string esbID, string data) {
            CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequestBody();
            inValue.Body.toNode = toNode;
            inValue.Body.esbID = esbID;
            inValue.Body.data = data;
            CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).callNPP4EDI(inValue);
            return retVal.Body.callNPP4EDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.callNPP4EDIAsync(CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest request) {
            return base.Channel.callNPP4EDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIResponse> callNPP4EDIAsync(string toNode, string esbID, string data) {
            CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.callNPP4EDIRequestBody();
            inValue.Body.toNode = toNode;
            inValue.Body.esbID = esbID;
            inValue.Body.data = data;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).callNPP4EDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.getBookTime(CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest request) {
            return base.Channel.getBookTime(request);
        }
        
        public string getBookTime(string preDate, out string errorMsg, out string errorCode) {
            CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequestBody();
            inValue.Body.preDate = preDate;
            CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).getBookTime(inValue);
            errorMsg = retVal.Body.errorMsg;
            errorCode = retVal.Body.errorCode;
            return retVal.Body.getBookTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.getBookTimeAsync(CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest request) {
            return base.Channel.getBookTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.getBookTimeResponse> getBookTimeAsync(string preDate) {
            CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.getBookTimeRequestBody();
            inValue.Body.preDate = preDate;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).getBookTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.reserveResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.reserve(CMICT.CSP.Web.BusinessOnlineServices.reserveRequest request) {
            return base.Channel.reserve(request);
        }
        
        public string reserve(string containerNo, string bLNo, string reserved, string handled, out string errorMsg, out string errorCode) {
            CMICT.CSP.Web.BusinessOnlineServices.reserveRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.reserveRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.reserveRequestBody();
            inValue.Body.containerNo = containerNo;
            inValue.Body.bLNo = bLNo;
            inValue.Body.reserved = reserved;
            inValue.Body.handled = handled;
            CMICT.CSP.Web.BusinessOnlineServices.reserveResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).reserve(inValue);
            errorMsg = retVal.Body.errorMsg;
            errorCode = retVal.Body.errorCode;
            return retVal.Body.reserveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.reserveResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.reserveAsync(CMICT.CSP.Web.BusinessOnlineServices.reserveRequest request) {
            return base.Channel.reserveAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.reserveResponse> reserveAsync(string containerNo, string bLNo, string reserved, string handled) {
            CMICT.CSP.Web.BusinessOnlineServices.reserveRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.reserveRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.reserveRequestBody();
            inValue.Body.containerNo = containerNo;
            inValue.Body.bLNo = bLNo;
            inValue.Body.reserved = reserved;
            inValue.Body.handled = handled;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).reserveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.reserveContainers(CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest request) {
            return base.Channel.reserveContainers(request);
        }
        
        public string reserveContainers(string containers, string reserveDate, string customer, string linkman, string phone, out string errorMsg, out string errorCode) {
            CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequestBody();
            inValue.Body.containers = containers;
            inValue.Body.reserveDate = reserveDate;
            inValue.Body.customer = customer;
            inValue.Body.linkman = linkman;
            inValue.Body.phone = phone;
            CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).reserveContainers(inValue);
            errorMsg = retVal.Body.errorMsg;
            errorCode = retVal.Body.errorCode;
            return retVal.Body.reserveContainersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.reserveContainersAsync(CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest request) {
            return base.Channel.reserveContainersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.reserveContainersResponse> reserveContainersAsync(string containers, string reserveDate, string customer, string linkman, string phone) {
            CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.reserveContainersRequestBody();
            inValue.Body.containers = containers;
            inValue.Body.reserveDate = reserveDate;
            inValue.Body.customer = customer;
            inValue.Body.linkman = linkman;
            inValue.Body.phone = phone;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).reserveContainersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.costcoOutGateSearch(CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest request) {
            return base.Channel.costcoOutGateSearch(request);
        }
        
        public string costcoOutGateSearch(string outDateStar, string outDateEnds) {
            CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequestBody();
            inValue.Body.outDateStar = outDateStar;
            inValue.Body.outDateEnds = outDateEnds;
            CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).costcoOutGateSearch(inValue);
            return retVal.Body.costcoOutGateSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.costcoOutGateSearchAsync(CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest request) {
            return base.Channel.costcoOutGateSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchResponse> costcoOutGateSearchAsync(string outDateStar, string outDateEnds) {
            CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.costcoOutGateSearchRequestBody();
            inValue.Body.outDateStar = outDateStar;
            inValue.Body.outDateEnds = outDateEnds;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).costcoOutGateSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponse CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.costcoContainerSearch(CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest request) {
            return base.Channel.costcoContainerSearch(request);
        }
        
        public string costcoContainerSearch(string containerId, string businessType) {
            CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequestBody();
            inValue.Body.containerId = containerId;
            inValue.Body.businessType = businessType;
            CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponse retVal = ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).costcoContainerSearch(inValue);
            return retVal.Body.costcoContainerSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponse> CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap.costcoContainerSearchAsync(CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest request) {
            return base.Channel.costcoContainerSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchResponse> costcoContainerSearchAsync(string containerId, string businessType) {
            CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest inValue = new CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequest();
            inValue.Body = new CMICT.CSP.Web.BusinessOnlineServices.costcoContainerSearchRequestBody();
            inValue.Body.containerId = containerId;
            inValue.Body.businessType = businessType;
            return ((CMICT.CSP.Web.BusinessOnlineServices.QGCostcoSoap)(this)).costcoContainerSearchAsync(inValue);
        }
    }
}
