//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMICT.CSP.Web.BusinessSearch.DataSourceManage {
    using System.Web.UI.WebControls.Expressions;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using Wuqi.Webdiyer;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.CodeDom.Compiler;
    
    
    public partial class DataSourceManage {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button lbtndel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidpagesize;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidsourceid;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidisdefault;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidtitle;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSourceName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlCATEGORY;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlsmallcategory;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlDataType;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSourceIP;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtDBName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtObjectName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Repeater DataSourceList;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lblnodata;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Wuqi.Webdiyer.AspNetPager AspNetPager1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DataSourceManage target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControllbtndel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.lbtndel = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbtndel";
            @__ctrl.Text = "删除用";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            @__ctrl.CssClass = "lbtndel";
            @__ctrl.Click -= new System.EventHandler(this.lbtndel_Click);
            @__ctrl.Click += new System.EventHandler(this.lbtndel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidpagesize() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidpagesize = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidpagesize";
            @__ctrl.Value = "20";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidpagesize");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidsourceid() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidsourceid = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidsourceid";
            @__ctrl.Value = "";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidsourceid");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidisdefault() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidisdefault = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidisdefault";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidisdefault");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidtitle() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidtitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidtitle";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidtitle");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSourceName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSourceName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSourceName";
            @__ctrl.CssClass = "stepIpt widthMaxSource fLeft";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlCATEGORY() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlCATEGORY = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlCATEGORY";
            @__ctrl.CssClass = "default widthMaxSource ddlCATEGORY";
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlCATEGORY_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlCATEGORY_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlsmallcategory() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlsmallcategory = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlsmallcategory";
            @__ctrl.CssClass = "default widthMaxSource ddlsmallcategory";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlDataType() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlDataType = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlDataType";
            @__ctrl.CssClass = "default widthMaxSource";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlStatus() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlStatus = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlStatus";
            @__ctrl.CssClass = "default widthMaxSource";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSourceIP() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSourceIP = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSourceIP";
            @__ctrl.CssClass = "stepIpt widthMaxSource fLeft";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtDBName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtDBName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtDBName";
            @__ctrl.CssClass = "stepIpt widthMaxSource fLeft";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtObjectName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtObjectName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtObjectName";
            @__ctrl.CssClass = "stepIpt widthMaxSource fLeft";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSearch() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSearch = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSearch";
            @__ctrl.Text = "查询";
            @__ctrl.OnClientClick = "layer.load(\'查询中，请稍候...\');";
            @__ctrl.CssClass = "operationBtn query btnhsearch fLeft";
            @__ctrl.Click -= new System.EventHandler(this.btnSearch_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSearch_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control4() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "SourceName";
            @__ctrl.Text = "数据源名称";
            @__ctrl.CommandName = "SourceName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control5() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DBName";
            @__ctrl.Text = "数据库名称";
            @__ctrl.CommandName = "DBName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control6() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ObjectType";
            @__ctrl.Text = "数据获取类型";
            @__ctrl.CommandName = "ObjectType";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control7() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ObjectName";
            @__ctrl.Text = "内部名称";
            @__ctrl.CommandName = "ObjectName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control8() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "BigCategory";
            @__ctrl.Text = "报表大类";
            @__ctrl.CommandName = "BigCategory";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control9() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "SmallCategory";
            @__ctrl.Text = "报表细类";
            @__ctrl.CommandName = "SmallCategory";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control10() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "SourceStatus";
            @__ctrl.Text = "状态";
            @__ctrl.CommandName = "SourceStatus";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px; font-family: \'Microsoft YaHei\', 微软雅黑, Arial, Helvetica, sans-ser" +
                    "if; color: rgb(68, 68, 68);");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control3(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <thead>\r\n                            <tr>\r\n            " +
                        "                    <th style=\"width: 142px;\">\r\n                                " +
                        "    "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th style=\"width: 102px;\">数据库服务器地址</th>\r\n " +
                        "                               <th style=\"width: 97px;\">\r\n                      " +
                        "              "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control5();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th style=\"width: 77px;\">\r\n               " +
                        "                     "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control6();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th style=\"width: 127px;\">\r\n              " +
                        "                      "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control7();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th style=\"width: 120px;\">\r\n              " +
                        "                      "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control8();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th style=\"width: 120px;\">\r\n              " +
                        "                      "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control9();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th style=\"width: 140px;\">模板名称</th>\r\n     " +
                        "                           <th style=\"width: 30px;\">\r\n                          " +
                        "          "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control10();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</th>\r\n                                <th class=\"lastMenu\" style=\"width: 92px; w" +
                        "ord-wrap: break-word;\">操作</th>\r\n                            </tr>\r\n             " +
                        "           </thead>\r\n                        <tbody>\r\n                    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control12() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(13, 12);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                        <tr>\r\n                            <td style=\"word-wrap:" +
                    " break-word; word-break: break-all; width: 142px;\">");
            @__ctrl.SetStaticString(1, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 102px;\">");
            @__ctrl.SetStaticString(2, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 97px;\">");
            @__ctrl.SetStaticString(3, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 77px;\">");
            @__ctrl.SetStaticString(4, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 127px;\">");
            @__ctrl.SetStaticString(5, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 120px;\">");
            @__ctrl.SetStaticString(6, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 120px;\">");
            @__ctrl.SetStaticString(7, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 140px;\">");
            @__ctrl.SetStaticString(8, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 30px;\">");
            @__ctrl.SetStaticString(9, "</td>\r\n                            <td style=\"word-wrap: break-word; word-break: " +
                    "break-all; width: 92px;\">\r\n                                <a class=\"operateBtn " +
                    "edit\" href=\"ConnectionConfig.aspx?sourceID=");
            @__ctrl.SetStaticString(10, "\" title=\"编辑\" target=\"_parent\"></a>\r\n                                <a class=\"ope" +
                    "rateBtn remove\" href=\"javascript:void(0);\" title=\"删除\" onclick=\"executedel(\'");
            @__ctrl.SetStaticString(11, "\');\" style=\'");
            @__ctrl.SetStaticString(12, "\'></a>\r\n                            </td>\r\n                        </tr>\r\n       " +
                    "             ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control12);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        public void @__DataBind__control12(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("SourceName"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("SourceIP"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(2, global::System.Convert.ToString(Eval("DBName"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(3, global::System.Convert.ToString(CMICT.CSP.BLL.Components.BaseComponent.GetLookupNameBuValue("BS_OBJECT_TYPE",Convert.ToString(Eval("ObjectType"))), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(4, global::System.Convert.ToString(Eval("ObjectName"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(5, global::System.Convert.ToString(CMICT.CSP.BLL.Components.BaseComponent.GetUserTypeNameByCode(Convert.ToString(Eval("BigCategory"))), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(6, global::System.Convert.ToString(CMICT.CSP.BLL.Components.BaseComponent.GetUserLookupNameBuValue(Convert.ToString(Eval("BigCategory")),Convert.ToString(Eval("SmallCategory"))), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(7, global::System.Convert.ToString(GetTemplateInfoBySourceID(Convert.ToString(Eval("SourceID"))), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(8, global::System.Convert.ToString(CMICT.CSP.BLL.Components.BaseComponent.GetLookupNameBuValue("BS_SOURCE_STATUS",Convert.ToString(Eval("SourceStatus"))), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(9, global::System.Convert.ToString(Eval("SourceID"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(10, global::System.Convert.ToString(Eval("SourceID"), global::System.Globalization.CultureInfo.CurrentCulture));
            target.SetDataBoundString(11, global::System.Convert.ToString((Convert.ToString(Eval("SourceStatus"))=="ENABLE")? "display:none": "", global::System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control11(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control12();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlDataSourceList() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            this.DataSourceList = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.HeaderTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control3));
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control11));
            @__ctrl.ID = "DataSourceList";
            @__ctrl.ItemCommand -= new System.Web.UI.WebControls.RepeaterCommandEventHandler(this.TemplateList_ItemCommand);
            @__ctrl.ItemCommand += new System.Web.UI.WebControls.RepeaterCommandEventHandler(this.TemplateList_ItemCommand);
            @__ctrl.ItemDataBound -= new System.Web.UI.WebControls.RepeaterItemEventHandler(this.TemplateList_ItemDataBound);
            @__ctrl.ItemDataBound += new System.Web.UI.WebControls.RepeaterItemEventHandler(this.TemplateList_ItemDataBound);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllblnodata() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblnodata = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblnodata";
            @__ctrl.Text = "暂无数据！";
            @__ctrl.Visible = false;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "font-size: 12px;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Wuqi.Webdiyer.AspNetPager @__BuildControlAspNetPager1() {
            global::Wuqi.Webdiyer.AspNetPager @__ctrl;
            @__ctrl = new global::Wuqi.Webdiyer.AspNetPager();
            this.AspNetPager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "AspNetPager1";
            @__ctrl.PageSize = 20;
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CssClass = "pageList";
            @__ctrl.NumericButtonCount = 5;
            @__ctrl.ShowMoreButtons = true;
            @__ctrl.AlwaysShow = true;
            @__ctrl.FirstPageText = "首页";
            @__ctrl.LastPageText = "尾页";
            @__ctrl.NextPageText = "下一页";
            @__ctrl.PrevPageText = "上一页";
            @__ctrl.SubmitButtonText = "Go";
            @__ctrl.SubmitButtonClass = "gostyle";
            @__ctrl.CustomInfoStyle = "font-size:14px;text-align:right;padding-top: 2px;";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("InputBoxStyle", "width:25px; border:1px solid #999999; text-align:center; ");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("TextBeforeInputBox", "转到第");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("TextAfterInputBox", "页 ");
            @__ctrl.PageIndexBoxType = global::Wuqi.Webdiyer.PageIndexBoxType.TextBox;
            @__ctrl.ShowPageIndexBox = global::Wuqi.Webdiyer.ShowPageIndexBox.Always;
            @__ctrl.TextAfterPageIndexBox = "页";
            @__ctrl.TextBeforePageIndexBox = "转到";
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(14D, global::System.Web.UI.WebControls.UnitType.Pixel));
            @__ctrl.ShowCustomInfoSection = global::Wuqi.Webdiyer.ShowCustomInfoSection.Right;
            @__ctrl.CustomInfoSectionWidth = new System.Web.UI.WebControls.Unit(15D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.PagingButtonSpacing = new System.Web.UI.WebControls.Unit(3D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.CustomInfoHTML = @"共<font color='#ff0000'>%RecordCount%</font>条  每页显示<select id='pcount' class='default pcount' onchange='changesize(this.options[this.options.selectedIndex].value)'><option value='5'>5</option><option value='10'>10</option><option value='15'>15</option><option value='20' selected>20</option><option value='30'>30</option><option value='40'>40</option><option value='50'>50</option></select></div>";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            @__ctrl.PageChanged -= new System.EventHandler(this.AspNetPager1_PageChanged);
            @__ctrl.PageChanged += new System.EventHandler(this.AspNetPager1_PageChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.Button @__ctrl1;
            @__ctrl1 = this.@__BuildControllbtndel();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl2;
            @__ctrl2 = this.@__BuildControlhidpagesize();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl3;
            @__ctrl3 = this.@__BuildControlhidsourceid();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl4;
            @__ctrl4 = this.@__BuildControlhidisdefault();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl5;
            @__ctrl5 = this.@__BuildControlhidtitle();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtSourceName();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.DropDownList @__ctrl7;
            @__ctrl7 = this.@__BuildControlddlCATEGORY();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.DropDownList @__ctrl8;
            @__ctrl8 = this.@__BuildControlddlsmallcategory();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.DropDownList @__ctrl9;
            @__ctrl9 = this.@__BuildControlddlDataType();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.DropDownList @__ctrl10;
            @__ctrl10 = this.@__BuildControlddlStatus();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            @__ctrl11 = this.@__BuildControltxtSourceIP();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            @__ctrl12 = this.@__BuildControltxtDBName();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.WebControls.TextBox @__ctrl13;
            @__ctrl13 = this.@__BuildControltxtObjectName();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.WebControls.Button @__ctrl14;
            @__ctrl14 = this.@__BuildControlbtnSearch();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.WebControls.Repeater @__ctrl15;
            @__ctrl15 = this.@__BuildControlDataSourceList();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.WebControls.Label @__ctrl16;
            @__ctrl16 = this.@__BuildControllblnodata();
            @__parser.AddParsedSubObject(@__ctrl16);
            global::Wuqi.Webdiyer.AspNetPager @__ctrl17;
            @__ctrl17 = this.@__BuildControlAspNetPager1();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control2));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n        ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write(@"
        <div class=""filterBox"">
            <div class=""filterIptBox"">
                <table class=""filterTable"">
                    <tr>
                        <td class=""filterTxtWidth"">
                            <label class=""filterIptTxt fLeft"">数据源名称：</label></td>
                        <td>
                            ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("</td>\r\n                        <td class=\"filterTxtWidth\">\r\n                     " +
                    "       <label class=\"filterIptTxt fLeft\">报表大类：</label></td>\r\n                   " +
                    "     <td>\r\n                            ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("</td>\r\n                        <td class=\"filterTxtWidth\">\r\n                     " +
                    "       <label class=\"filterIptTxt fLeft\">报表细类：</label></td>\r\n                   " +
                    "     <td>\r\n                            ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("</td>\r\n                        <td class=\"filterTxtWidth\">\r\n                     " +
                    "       <label class=\"filterIptTxt fLeft\">数据获取类型：</label></td>\r\n                 " +
                    "       <td>\r\n                            ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("</td>\r\n                    </tr>\r\n                    <tr>\r\n                     " +
                    "   <td>\r\n                            <label class=\"filterIptTxt fLeft\">状态：</labe" +
                    "l></td>\r\n                        <td>\r\n                            ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("</td>\r\n                        <td class=\"filterTxtWidth130\">\r\n                  " +
                    "          <label class=\"filterIptTxt fLeft\">数据库服务器地址：</label></td>\r\n            " +
                    "            <td>\r\n                            ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("</td>\r\n                        <td>\r\n                            <label class=\"fi" +
                    "lterIptTxt fLeft\">数据库名称：</label></td>\r\n                        <td>\r\n           " +
                    "                 ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("</td>\r\n                        <td>\r\n                            <label class=\"fi" +
                    "lterIptTxt fLeft\">内部名称：</label></td>\r\n                        <td>\r\n            " +
                    "                ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write(@"</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td colspan=""3"">
                            <div class=""operationBox"">
                                <ul class=""operationBtnBox"">
                                    <li>
                                        <a class=""addFiltrateBtnAstyle fLeft"" href=""");
                                                                            @__w.Write(CMICT.CSP.BLL.Components.BaseComponent.GetReportTypeUrl() );

            @__w.Write(@""" target=""_blank"">新建报表类别</a>
</li>
                                    <li>
                                    <a class=""operationBtn query fLeft"" href=""ConnectionConfig.aspx"" target=""_parent"">添加</a>
                                    </li>
                                    <li>
                                        ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write(@"
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                </table>

            </div>
        </div>

        <div class=""cutOffRule clearBoth""></div>

        <div class=""resultBox"">
            <table class=""tableOne tableOneLayout"">
                ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n                </tbody>                       \r\n            </table>\r\n        " +
                    "    ");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n\r\n        <div class=\"pageBox\">\r\n            ");
            parameterContainer.Controls[16].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n\r\n    ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanel1 = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "UpdatePanel1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::CMICT.CSP.Web.BusinessSearch.DataSourceManage.DataSourceManage @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
<style type=""text/css"">
    .widthMaxSource {
    width: 100% !important;
    min-width: 130px;
    height: 30px;
    line-height: 28px;
}
    .costDesSource {
        width: 100% !important;
        display: inline-block;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
</style>

"));
            global::System.Web.UI.UpdatePanel @__ctrl1;
            @__ctrl1 = this.@__BuildControlUpdatePanel1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<script type=\"text/javascript\">\r\n    //给数据源下拉加title  dk_toggle dk_label\r\n    fu" +
                        "nction addtiptodropdown() {\r\n        $(\"div[id*=\'ddlCATEGORY\']\").find(\"a\").each(" +
                        "function () {\r\n            var atipname = $(this).html();\r\n            $(this).a" +
                        "ttr(\"title\", atipname).addClass(\"costDesSource\");\r\n        });\r\n        $(\"div[i" +
                        "d*=\'ddlsmallcategory\']\").find(\"a\").each(function () {\r\n            var atipname " +
                        "= $(this).html();\r\n            $(this).attr(\"title\", atipname).addClass(\"costDes" +
                        "Source\");\r\n        });\r\n    }\r\n    var prm = Sys.WebForms.PageRequestManager.get" +
                        "Instance();\r\n    prm.add_beginRequest(function () {\r\n\r\n    });\r\n    prm.add_endR" +
                        "equest(function (sender, args) {\r\n        args.set_errorHandled(true);\r\n        " +
                        "try {\r\n            if ($(\'.default\').length > 0) {\r\n                $(\'.default\'" +
                        ").dropkick();\r\n            }\r\n            layer.closeAll();\r\n            $(docum" +
                        "ent).attr(\"title\", $(\".hidtitle\").val());\r\n            addtiptodropdown();\r\n    " +
                        "    } catch (err) {\r\n\r\n        }\r\n    });\r\n    function executedel(sid) {\r\n     " +
                        "   $(\".hidsourceid\").val(sid);\r\n        var msg = \"您确定要删除吗？\";\r\n        RegisterB" +
                        "uttonConfirm(msg, 1);\r\n        return false;\r\n    }\r\n    //注册确认方法\r\n    function " +
                        "RegisterButtonConfirm(msgs, type) {\r\n        var iss = 0;\r\n        var yes = \'确定" +
                        "\';\r\n        var no = \'取消\';\r\n        $.layer({\r\n            shade: [0.5, \'#000\', " +
                        "true],\r\n            area: [\'auto\', \'auto\'],\r\n            dialog: {\r\n            " +
                        "    msg: msgs,\r\n                btns: 2,\r\n                type: 4,\r\n            " +
                        "    btn: [yes, no],\r\n                yes: function (index) {\r\n                  " +
                        "  layer.close(index);\r\n                    if (type == 1) {\r\n                   " +
                        "     $(\".lbtndel\").click();\r\n                    }\r\n                },\r\n        " +
                        "        no: function () {\r\n                }\r\n            }\r\n        });\r\n      " +
                        "  if (iss == 1) {\r\n            return true;\r\n        } else {\r\n            retur" +
                        "n false;\r\n        }\r\n    }\r\n    function AddDataSource() {\r\n        $.layer({\r\n " +
                        "           type: 2,\r\n            title: \'添加数据源\',\r\n            maxmin: false,\r\n  " +
                        "          border: [0],\r\n            shadeClose: false, //  \r\n            area: [" +
                        "\'610px\', \'530px\'],\r\n            offset: [\'98px\', \'\'],\r\n            iframe: { src" +
                        ": \'ConnectionConfig.aspx?isContent=1\', scrolling: \'no\' }\r\n        });\r\n        r" +
                        "eturn false;\r\n    }\r\n    $(function ($) {\r\n        $(\".hidtitle\").val($(document" +
                        ").attr(\"title\"));\r\n        addtiptodropdown();\r\n    });\r\n    //禁止回车事件响应\r\n    $(t" +
                        "his).keydown(function (e) {\r\n        var key = window.event ? e.keyCode : e.whic" +
                        "h;\r\n        //alert(key.toString());\r\n        if (key.toString() == \"13\") {\r\n   " +
                        "         return false;\r\n        }\r\n    });\r\n</script>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
