//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMICT.CSP.Web.TemplateConfig.DataSourceConfig {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class DataSourceConfig {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlCATEGORY;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtCATEGORY;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlsmallcategory;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtsmallcategory;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlSourceName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSourceName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton lbtnPrev;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton lbtnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button Button1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidOperType;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidsourceid;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidtipcontent;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidtitle;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DataSourceConfig target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlCATEGORY() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlCATEGORY = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlCATEGORY";
            @__ctrl.CssClass = "default w210 ddlCATEGORY";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "changecatebig();");
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlCATEGORY_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlCATEGORY_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCATEGORY() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCATEGORY = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCATEGORY";
            @__ctrl.CssClass = "txtCATEGORY";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "报表大类~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlsmallcategory() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlsmallcategory = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlsmallcategory";
            @__ctrl.CssClass = "default w210 ddlsmallcategory";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "changesmallcategory();");
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlsmallcategory_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlsmallcategory_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtsmallcategory() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtsmallcategory = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtsmallcategory";
            @__ctrl.CssClass = "txtsmallcategory";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "报表细类~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlSourceName() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlSourceName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlSourceName";
            @__ctrl.CssClass = "default w210 ddlSourceName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "changesname();");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSourceName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSourceName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSourceName";
            @__ctrl.CssClass = "txtSourceName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("title", "数据源名称~50:!");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onchange", "deoxidizevalidate(this)");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbtnPrev() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbtnPrev = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbtnPrev";
            @__ctrl.CssClass = "guideBtn prevLink";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("上一步"));
            @__ctrl.Click -= new System.EventHandler(this.lbtnPrev_Click);
            @__ctrl.Click += new System.EventHandler(this.lbtnPrev_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbtnSave() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbtnSave = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbtnSave";
            @__ctrl.CssClass = "guideBtn nextLink";
            @__ctrl.OnClientClick = "return executesub();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("下一步"));
            @__ctrl.Click -= new System.EventHandler(this.lbtnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.lbtnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlButton1() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.Button1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Button1";
            @__ctrl.Text = "修改用";
            @__ctrl.CssClass = "btnsave";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "display: none;");
            @__ctrl.Click -= new System.EventHandler(this.lbtnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.lbtnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidOperType() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidOperType = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidOperType";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidOperType");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidsourceid() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidsourceid = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidsourceid";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidsourceid");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidtipcontent() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidtipcontent = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidtipcontent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidtipcontent");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhidtitle() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hidtitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hidtitle";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "hidtitle");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlCATEGORY();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtCATEGORY();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlddlsmallcategory();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtsmallcategory();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.DropDownList @__ctrl5;
            @__ctrl5 = this.@__BuildControlddlSourceName();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtSourceName();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.LinkButton @__ctrl7;
            @__ctrl7 = this.@__BuildControllbtnPrev();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.LinkButton @__ctrl8;
            @__ctrl8 = this.@__BuildControllbtnSave();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.Button @__ctrl9;
            @__ctrl9 = this.@__BuildControlButton1();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl10;
            @__ctrl10 = this.@__BuildControlhidOperType();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl11;
            @__ctrl11 = this.@__BuildControlhidsourceid();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl12;
            @__ctrl12 = this.@__BuildControlhidtipcontent();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl13;
            @__ctrl13 = this.@__BuildControlhidtitle();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control2));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n        <div class=\"stepOperateBox\">\r\n            <table class=\"tableTwo\">\r\n   " +
                    "             <tr>\r\n                    <td>\r\n                        <label clas" +
                    "s=\"stepIptTxt\">报表大类：</label></td>\r\n                    <td>\r\n                   " +
                    "     ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("<span class=\"mustIcon\">*</span>\r\n                        ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                    </td>\r\n                    <td>\r\n                        <d" +
                    "iv id=\"div");
                             @__w.Write(txtCATEGORY.ClientID );

            @__w.Write(@"""></div>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <label class=""stepIptTxt"">报表细类：</label></td>
                    <td>
                        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                        <span class=\"mustIcon\">*</span>\r\n                      " +
                    "  ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                    </td>\r\n                    <td>\r\n                        <d" +
                    "iv id=\"div");
                             @__w.Write(txtsmallcategory.ClientID );

            @__w.Write(@"""></div>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <label class=""stepIptTxt"">数据源名称：</label></td>
                    <td>
                        ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n                        <span class=\"mustIcon\">*</span>\r\n                      " +
                    "  ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n                    </td>\r\n                    <td>\r\n                        <d" +
                    "iv id=\"div");
                             @__w.Write(txtSourceName.ClientID );

            @__w.Write(@"""></div>
                    </td>
                    <td><a class=""addFiltrateBtnAstyle"" href=""DataSourceManage.aspx"" target=""_blank"">新建数据源</a></td>
                </tr>
            </table>
            <div class=""cutOffRule""></div>
            <div class=""operateBtnBox operateBtnLayout"">
                ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n        </div>\r\n        ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n    ");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel2() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanel2 = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "UpdatePanel2";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::CMICT.CSP.Web.TemplateConfig.DataSourceConfig.DataSourceConfig @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<div class=""progressBox"">
    <ul class=""progressStepBox"">
        <li>
            <div class=""stepBox stepPrev"">
                <p>1.基本信息配置</p>
                <span></span>
            </div>
        </li>
        <li>
            <div class=""stepBox stepcurrent"">
                <p>2.配置数据源</p>
                <span></span>
            </div>
        </li>
        <li>
            <div class=""stepBox"">
                <p>3.配置展示方式</p>
                <span></span>
            </div>
        </li>
        <li>
            <div class=""stepBox"">
                <p>4.配置筛选条件</p>
                <span></span>
            </div>
        </li>
        <li>
            <div class=""stepBox"">
                <p>5.配置业务信息查询通信</p>
            </div>
        </li>
    </ul>
</div>
<div class=""cutOffRule""></div>
"));
            global::System.Web.UI.UpdatePanel @__ctrl1;
            @__ctrl1 = this.@__BuildControlUpdatePanel2();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script type=\"text/javascript\">\r\n    $(function ($) {\r\n        addtiptodropdo" +
                        "wn();\r\n        addtiptodbname();\r\n        $(\".hidtitle\").val($(document).attr(\"t" +
                        "itle\"));\r\n    });\r\n    var prm = Sys.WebForms.PageRequestManager.getInstance();\r" +
                        "\n    prm.add_beginRequest(function () {\r\n\r\n    });\r\n    prm.add_endRequest(funct" +
                        "ion (sender, args) {\r\n        args.set_errorHandled(true);\r\n        try {\r\n     " +
                        "       if ($(\'.default\').length > 0) {\r\n                $(\'.default\').dropkick()" +
                        ";\r\n                addtiptodbname();\r\n                addtiptodropdown();\r\n     " +
                        "       }\r\n            $(document).attr(\"title\", $(\".hidtitle\").val());\r\n        " +
                        "} catch (err) {\r\n\r\n        }\r\n    });\r\n    //给数据源下拉加title\r\n    function addtipto" +
                        "dbname() {\r\n        var sourcenametip = $(\".hidtipcontent\").val();\r\n        if (" +
                        "$.trim(sourcenametip) != \"\") {\r\n            var stiplist = sourcenametip.split(\'" +
                        "!\');\r\n            $(\"div[id*=\'ddlSourceName\']\").find(\"a\").each(function () {\r\n  " +
                        "              if ($(this).attr(\"data-dk-dropdown-value\") != undefined && $(this)" +
                        ".attr(\"data-dk-dropdown-value\") != null && $(this).attr(\"data-dk-dropdown-value\"" +
                        ") != \"\") {\r\n                    var atipname = $(this).attr(\"data-dk-dropdown-va" +
                        "lue\");\r\n                    for (var i = 0; i < stiplist.length; i++) {\r\n       " +
                        "                 if (stiplist[i].indexOf(atipname) != -1) {\r\n                   " +
                        "         $(this).attr(\"title\", stiplist[i].split(\',\')[1]);\r\n                    " +
                        "        break;\r\n                        }\r\n                    }\r\n              " +
                        "  }\r\n            });\r\n        }\r\n    }\r\n    //给数据源下拉加title  dk_toggle dk_label\r\n" +
                        "    function addtiptodropdown() {\r\n        $(\"div[id*=\'ddlCATEGORY\']\").find(\"a\")" +
                        ".each(function () {\r\n                var atipname = $(this).html();\r\n           " +
                        "     $(this).attr(\"title\", atipname).addClass(\"costDes\");\r\n        });\r\n        " +
                        "$(\"div[id*=\'ddlsmallcategory\']\").find(\"a\").each(function () {\r\n            var a" +
                        "tipname = $(this).html();\r\n            $(this).attr(\"title\", atipname).addClass(" +
                        "\"costDes\");\r\n        });\r\n    }\r\n    function executesub() {\r\n        var b_retu" +
                        "rn = checkForm(document.forms.item(0, null));\r\n        var sid = $.trim($(\".hids" +
                        "ourceid\").val());\r\n        var oldsid = $.trim($(\".ddlSourceName option:selected" +
                        "\").val());\r\n        var optype = $.trim($(\".hidOperType\").val());\r\n        if (o" +
                        "ptype != \"edit\") {//新增\r\n            return b_return;\r\n        } else {\r\n        " +
                        "    if (b_return) {\r\n                if (sid != oldsid) {\r\n                    v" +
                        "ar msg = \"更改数据源将会影响业务逻辑的查询，您确定要更改吗？\";\r\n                    RegisterButtonConfirm" +
                        "(msg, \'edit\');\r\n                } else {\r\n                    return true;\r\n    " +
                        "            }\r\n            }\r\n            return false;\r\n        }\r\n        retu" +
                        "rn false;\r\n    }\r\n    //注册确认方法groupcal\r\n    function RegisterButtonConfirm(msgs," +
                        " type) {\r\n        var iss = 0;\r\n        var yes = \'确定\';\r\n        var no = \'取消\';\r" +
                        "\n        $.layer({\r\n            shade: [0.5, \'#000\', true],\r\n            area: [" +
                        "\'auto\', \'auto\'],\r\n            dialog: {\r\n                msg: msgs,\r\n           " +
                        "     btns: 2,\r\n                type: 4,\r\n                btn: [yes, no],\r\n      " +
                        "          yes: function (index) {\r\n                    layer.close(index);\r\n    " +
                        "                if (type == \"edit\") {\r\n                        $(\".btnsave\").cli" +
                        "ck();\r\n                    }\r\n                },\r\n                no: function (" +
                        ") {\r\n                }\r\n            }\r\n        });\r\n    }\r\n    function changeca" +
                        "tebig() {\r\n        $(\".txtCATEGORY\").val($(\".ddlCATEGORY option:selected\").val()" +
                        ");\r\n        $(\".txtCATEGORY\").change();\r\n    }\r\n\r\n    function changesmallcatego" +
                        "ry() {\r\n        $(\".txtsmallcategory\").val($(\".ddlsmallcategory option:selected\"" +
                        ").val());\r\n        $(\".txtsmallcategory\").change();\r\n    }\r\n    function changes" +
                        "name() {\r\n        $(\".txtSourceName\").val($(\".ddlSourceName option:selected\").va" +
                        "l());\r\n        $(\".txtSourceName\").change();\r\n    }\r\n</script>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
